INSERT INTO project(projectName, projectLead, projectDescription)VALUES('IT Fluency in non-human primates', 'Garret Arcoraci', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed dapibus ipsum. Vivamus urna diam, consequat vitae turpis vel, ornare fermentum purus');  		
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('How accessiblity influences change in ferret behavior', 'Catherine Beaton', 'Duis suscipit ac urna at rhoncus. Donec ut dictum justo. Mauris volutpat tempor aliquam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Web 3.0; Where is it?', 'Daniel Bogaard', 'Aliquam blandit, ante vel elementum scelerisque, quam lectus tempor nunc, et mattis diam mauris sit amet ex. Maecenas condimentum, velit non egestas congue, libero nulla commodo est, eget consectetur felis est id lectus.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('faculty tools related to abduction', 'Charlie Border', 'Proin magna diam, rhoncus vel nisi nec, maximus varius diam. Integer elit odio, pellentesque et congue at, sodales et sem.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('SOAP: not just for cleaning anymore', 'Stephen Cady', 'Suspendisse lacus diam, aliquet et sapien sit amet, aliquet dictum mauris. Etiam eros eros, suscipit in sagittis eu, iaculis ultrices tellus.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('PHP performance in tomcat data mining', 'Michael Floeser', 'Aliquam dictum ac diam id iaculis. Etiam congue, sapien ac viverra congue, justo quam auctor augue');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Web services, how did we get here?', 'Bryan French', 'ac pretium nunc magna et risus. Fusce non scelerisque ligula. Morbi in cursus nisl. Curabitur ornare lorem dolor, ut fringilla dui fermentum nec. Etiam euismod nunc sed felis ultricies condimentum');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('FITness in informatics', 'Erik Golen', 'Sed hendrerit nibh ut feugiat efficitur.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('IIS in Java', 'James Habermas', 'Sed bibendum diam sit amet nibh tincidunt, mattis porta leo mollis.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Cognitive Science in data mining', 'Vicki Hanson', 'Aliquam consectetur quis odio sit amet lobortis. Nullam eu fermentum elit, quis dapibus diam.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('C# and human memory', 'Bruce Hartpence', 'Vestibulum felis velit, pellentesque nec sapien ac, pulvinar congue nibh. Maecenas consequat nisi lorem, a feugiat nisl faucibus vitae. In eu congue enim, nec efficitur dui.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('XML as it relates to course assignments', 'Andrew Herbert', 'Mauris ac vulputate metus. Morbi in maximus tortor.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Cirriculum education', 'Larry Hill', 'Sed tempus pulvinar nunc at malesuada. ');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Databases are like human memory?', 'Ed Holden', 'Nullam sed dictum velit. ');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Departmental management and faculty rebellions', 'Matt Huenerfauth', 'Quisque rutrum pretium diam et faucibus. Mauris turpis ligula');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('XML and you', 'Sarah J. Huibregtse', 'lobortis id tortor a, sollicitudin convallis mi. ');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Java or PHP? Lets see that back end', 'Jai Kang', 'Nam viverra lacus vitae scelerisque bibendum. Etiam ut erat a quam aliquet egestas.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('net neutrality in the big data world', 'Jeffrey Lasky', 'In eget interdum sapien');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('SOAP: Actionable analytics', 'Jim Leone', 'vitae bibendum est. ');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Run for the hills: AI and Machine learning', 'Peter Lutz', 'Proin in rutrum arcu. ');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Personalization and voice recognition', 'Sharon Mason', 'Proin rutrum eros turpis, ac sodales massa dignissim in');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Chatbots: Not your mommas bots anymore', 'Michael McQuaid', 'Proin viverra ligula vel volutpat molestie');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('VR/AR/DR/PR and you', 'Tae (Tom) Oh', 'Aenean ac faucibus nisl, eu congue arcu');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Robotics and the smart factory of the future', 'David Patric', 'Vivamus in aliquet mauris');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Internet of things and Quantum Computing', 'Sylvia Perez-Hardy', 'eu convallis urna. Sed ac ');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Blockchain: Make it so', 'Jerry Powell', 'dapibus nunc, sit amet tincidunt ante');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Soup Lines: Technological unemployement and the coming catastrophe', 'Nirmala Shenoy', 'Fusce neque augue');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('WebDev in the Ai world', 'Kristen Shinohara', 'consectetur a lorem ac');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('systems administration and the WWW', 'Adam Smith', 'maximus vestibulum sem');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Mobile First design', 'Brian Tomaszewski', 'Fusce feugiat vehicula arcu nec porttitor.');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Why serverless archetecture is the future', 'Ronald Vullo', 'dolor sit amet, consectetur adipiscing elit. Ut sed dapibus ipsum. Vivamus');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Digital detox: take a break!', 'Elissa Weeden', 'diam, consequat vitae turpis vel, ornare ');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('microservices and blockchain', 'Qi Yu', 'velit non egestas congue, libero nulla commodo est');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('Dark data: who is watching the watchers?', 'Steve Zilora', 'eget consectetur felis est id lectus. Proin magna diam, rhoncus');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Julian Arya', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Andrew Berson', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Winston Chang', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Brandon Connors', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Samuel Evans', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Andrew Kukielka', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Vignesh Kumar', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Kevin Lozano', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Dishant Mishra', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Sylvia Mosquea Garcia', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Ellie Parobek', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Lorenzo Romero', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Luke Schwarting', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Rachael Simmonds', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Dominico Tran', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Clare Truell', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'ixhers Ajazi', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Kemoy Campbell', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Cameron Casselman', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Conner Catanese', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Daniel Chang', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'ikhail Chebotar', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Andrew Costanzo', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Tenzin Dhondup', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Zachary Easley', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Andrew Grubbs', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'nna Jacobsen', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Aaron Kelly', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Mei Ling Liu', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Amina Mahmood', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Brandon Mok', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Dale Moore', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Jacob OConnor', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Nicholas Porillo', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Abid Raja', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Demetri Sakellaropoulos', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Abbey Sands', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Charles Shaner', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Benjamin Thorn', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Kevin Voltz', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Alexander Yu Huang', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Mohammed Owaidh H Aljoha', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Shatha Naqa Alotaibi', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Abeer Ali H Alshehri', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Pallavi Arora', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Prajakta Prashant Deshpa', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Ryan Leonard', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Lekha Pramodkumar Nahar', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Mayuresh Pradeep Naik', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Vismay Ashok Pandit', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Sulagna Patra', '');
INSERT INTO project(projectName, projectLead, projectDescription)VALUES('', 'Shashank Prasanna Reddy', '');



